### ISSUE TITLE
Availability

### ISSUE THREAD

**Issue by thomassvensen** [dnasir/EPi.ContentTypeTools#10]
Hi!
I took the liberty of submitting your code to nuget.org, since we don't have a local nuget feed in our project: https://www.nuget.org/packages/EPi.ContentTypeTools/

I hope you don't mind, since the code was open-source already :-)

Regards
Thomas

**Comment by dnasir** [comment]
@thomassvensen Thanks for taking the initiative. I wanted to fix a couple of bugs before publishing the package, but haven't had much free time.

**Comment by thomassvensen** [comment]
Thank you for the approval! Are there known bugs, or were you thinking about the issues lists? Those seem to feature requests, not really bugs?
